audio:
  spec_duration: 3.0
  spec_height: 192
  spec_width: 384
  min_freq: 200
  max_freq: 13000
  win_length: .058
  sampling_rate: 28000
  choose_channel: true
infer:
  segment_len: null
hawkears:
  heuristics_manager: "hawkears.heuristics.canada.main.CanadaHeuristicsManager"
  save_rarities: true
